### PR TITLE
Workaround RHEL8 epel/fips feature for Fedora 42+

### LINKED ISSUE #3931: Failed to enable epel on RHEL-8.10
Enabling EPEL repo on RHEL 8.10 using the following prepare step fails due to an Ansible error.

```
prepare:
  - how: feature
    epel: enabled
    order: 40

```

```
prepare task #2: default-0 on default-0
        how: feature
        Enable EPEL
            cmd: ansible-playbook --ssh-common-args '-oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oIdentitiesOnly=yes -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip-ecdsa -oPasswordAuthentication=no -S/var/tmp/tmt/run-044/ssh-sockets/-root.socket' -i root@, /usr/lib/python3.13/site-packages/tmt/steps/prepare/feature/epel-enable.yaml
        fail: Command 'ansible-playbook --ssh-common-args '-oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oIdentitiesOnly=yes -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip-ecdsa -oPasswordAuthentication=no -S/var/tmp/tmt/run-044/ssh-sockets/-root.socket' -i root@, /usr/lib/python3.13/site-packages/tmt/steps/prepare/feature/epel-enable.yaml' returned 2.

plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    prepare step failed

    The exception was caused by 1 earlier exceptions

    Cause number 1:

        Command 'ansible-playbook --ssh-common-args '-oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectionAttempts=5 -oConnectTimeout=60 -oServerAliveInterval=5 -oServerAliveCountMax=60 -oIdentitiesOnly=yes -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip -i /var/tmp/tmt/run-044/plans/vdo/vdo_upgrade/provision/default-0/1minutetip-ecdsa -oPasswordAuthentication=no -S/var/tmp/tmt/run-044/ssh-sockets/-root.socket' -i root@, /usr/lib/python3.13/site-packages/tmt/steps/prepare/feature/epel-enable.yaml' returned 2.

        # stdout (7 lines)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PLAY [Enable EPEL repositories] ************************************************

        TASK [Gathering Facts] *********************************************************
        fatal: [root@]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "exception": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 44, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 951, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 894, in _find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1157, in find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1131, in _get_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1112, in _legacy_get_spec\r\n  File \"<frozen importlib._bootstrap>\", line 441, in spec_from_loader\r\n  File \"<frozen importlib._bootstrap_external>\", line 544, in spec_from_file_location\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_rklzb2x8/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 5\r\nSyntaxError: future feature annotations is not defined\r\n", "failed": true, "module_stderr": "Shared connection to  closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1753854391.0603848-14216-72338655721375/AnsiballZ_setup.py\", line 44, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 951, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 894, in _find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1157, in find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1131, in _get_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1112, in _legacy_get_spec\r\n  File \"<frozen importlib._bootstrap>\", line 441, in spec_from_loader\r\n  File \"<frozen importlib._bootstrap_external>\", line 544, in spec_from_file_location\r\n  File \"/tmp/ansible_ansible.legacy.setup_payload_rklzb2x8/ansible_ansible.legacy.setup_payload.zip/ansible/module_utils/basic.py\", line 5\r\nSyntaxError: future feature annotations is not defined\r\n", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform linux on host root@ is using the discovered Python interpreter at /usr/bin/python3, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information."]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}

PLAY RECAP *********************************************************************
        root@          : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        # stderr (6 lines)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        [WARNING]: Unhandled error in Python interpreter discovery for host
        root@: Expecting value: line 1 column 1 (char 0)
        [WARNING]: sftp transfer mechanism failed on [root@]. Use
        ANSIBLE_DEBUG=1 to see detailed information
        [WARNING]: scp transfer mechanism failed on [root@]. Use
        ANSIBLE_DEBUG=1 to see detailed information
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by thrix**
With Fedora42+ shipping Ansible-2.18+ the users get a failure when trying to connect to the remote host, because the default Python3.6 is not suported anymore.

We can workaround this by installing Python3.9 via modules, but `dnf` will not work well as there is no `python3-dnf` module for this Python version. So in the case of RHEL8 use `rpm` instead to install the `epel-release` package.

Note that this workaround will hopefully go away
with Testing Farm profiles, which should sort out this problem for all RHELs.

Enable `ubi8` tests to verify the feature.

Resolves #3931

Pull Request Checklist

* [x] implement the feature
* [x] extend the test coverage
* [x] include a release note

### CODE REVIEW

**Comment by thrix** [comment]
Opening as a draft for now, on my localhost I needed some fixes for ubi, maybe for CI not needed and I will rather open them separately.

File: tests/prepare/feature/epel/test.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ rlJournalStart
 
     # EPEL
     for image in $images; do
-        if rlIsFedora ">=42" && (is_centos_7 "$image" || is_ubi_8 "$image"); then
+	if rlIsFedora ">=42" && is_centos_7 "$image"; then
```
Comment (happz) [inline tests/prepare/feature/epel/test.sh]: Weird indentation change, tab vs spaces?

File: tmt/steps/prepare/feature/epel-disable.yaml [hunk 2]
```diff
@@ -1,5 +1,29 @@
 ---
 
+# Pre-setup to install Python 3.9 on RHEL/CentOS 8 systems
```
Comment (happz) [inline tmt/steps/prepare/feature/epel-disable.yaml:3]: Would it make sense to add this block to `fips-enable.yaml` too? It seems to me it would suffer the same problem, it is supposed to work on RHEL-8, `name: Enable FIPS mode on RHEL/CentosStream 8, 9 or 10`.

Comment (thrix) [reply tmt/steps/prepare/feature/epel-disable.yaml:3]: @happz I assume so, will check. Need another fix for 1MT anyway where the `epel-release` is already pre-installed ...

File: tests/prepare/feature/epel/test.sh (hunk 1 above)
Comment (thrix) [reply tests/prepare/feature/epel/test.sh]: yeah, some crap

File: tmt/steps/prepare/feature/epel-disable.yaml (hunk 2 above)
Comment (psss) [reply tmt/steps/prepare/feature/epel-disable.yaml:3]: Yeah, agreed, `fips` should be covered as well. Moving to the `implement` column.

File: tests/prepare/feature/epel/test.sh (hunk 1 above)
Comment (thrix) [reply tests/prepare/feature/epel/test.sh]: resolved

File: tmt/steps/prepare/feature/epel-enable.yaml [hunk 3]
```diff
@@ -1,5 +1,29 @@
...
+    - name: Install Python 3.9 on RHEL/CentOS 8 systems
+      ansible.builtin.raw: |
+        dnf -y module enable python39
+        dnf -y install python39
+      args:
+        executable: /bin/bash
+      when: |
+        'Red Hat Enterprise Linux release 8.' in release_out.stdout
+        or 'CentOS Linux release 8' in release_out.stdout
+        or 'CentOS Stream release 8' in release_out.stdout
```
[the remark this answers is not in the document]
Comment (thrix) [reply tmt/steps/prepare/feature/epel-enable.yaml:24]:
```
❯ podman run -it ubi8 cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.10 (Ootpa)
```

[the remark this answers is not in the document]
Comment (thrix) [reply tmt/steps/prepare/feature/epel-enable.yaml:24]: not really a :gem:

File: tmt/steps/prepare/feature/epel-disable.yaml (hunk 2 above)
Comment (thrix) [reply tmt/steps/prepare/feature/epel-disable.yaml:3]: @psss @happz fixed fips also

**Comment by tcornell-bus** [comment]
Should a test be added for `fips` as well?

File: tmt/steps/prepare/feature/epel-enable.yaml [hunk 4]
```diff
@@ -34,6 +58,21 @@
             name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"  # yamllint disable rule:line-length
             disable_gpg_check: true
             state: present
+          when: ansible_distribution_major_version | int >= 9
+
+        - name: Install package 'epel-release'
+
```
Comment (thrix) [inline tmt/steps/prepare/feature/epel-enable.yaml]:
```suggestion
```

**Review by tcornell-bus — APPROVED** [review]
Ran a test for `fips` on rhel-8.10 and then for `epel` on rhel-8.10. Both work as expected with these changes.

**Comment by thrix** [comment]
> Should a test be added for `fips` as well?

I was looking into it and the issue should be really reproducible on Fedora 42 with the container test against ubi8 image, so I believe it is covered. Although I am a bit surprised why it would not already fail, it really should. It did fail for me when testing.

**Review by happz — APPROVED** [review]
