### PR TITLE
Do not fetch disabled remote plans in `tmt run`

### LINKED ISSUE #2968: Is tmt plan import doing the actual import too early?
I was trying to add a condition around a test plan import but it didnt' work as expected.
E.g. this example with bogus url produces `git clone` error despite the plan being disabled.

```
/keylime-e2e:
  plan:
    import:
      url: hhttps://github.com/RedHat-SP-Security/keylime-plans.git
      name: /generic/minimal-e2e
  enabled: 0

$ tmt -c distro=rhel-10 run discover 
/var/tmp/tmt/run-015
    warn: /ci/keylime-e2e:enabled - 0 is not of type 'boolean'
fail: Command 'git clone hhttps://github.com/RedHat-SP-Security/keylime-plans.git /var/tmp/tmt/run-015/import/ci/keylime-e2e' returned 128.
```
Maybe the above is expected. I basically wanted to avoid fetching an internal URL for distros like Fedora or CS. For now I ended up with this which seems to work but looks unnecessarily complicated
```
/keylime-e2e:
  enabled: 0

  adjust:
   - when: distro == rhel
     enabled: 1
     plan:
      import:
        url: hhttps://github.com/RedHat-SP-Security/keylime-plans.git
        name: /generic/minimal-e2e
```
I am wondering if there is effectively any difference between these two approaches when the 1st one is doing the import early while the later one late. I can imagine that the imported plan may have also some adjust rules impacting plan status.

### PR DESCRIPTION
**Pull request by pkhartsk**
Fix #2968

Pull Request Checklist

* [x] implement the feature
* [x] extend the test coverage
* [x] include a release note

### CODE REVIEW

**Comment by happz** [comment]
@pkhartsk one note WRT naming, you seem to be using "imported" and "remote" incorrectly:

* "Do not fetch disabled remote plans in tmt run" - actually, whether the remote plan is disabled or not is not relevant to your PR, as it skips import resolution if the **importing** (or "local") plan is disabled. The title should be something like "Do not resolve importing plan when it is disabled".
* `/imported/disabled-by-adjust`, `summary: Imported plan should be disabled by default`,  `rlPhaseStartTest "Imported plan's import should not be resolved if disabled by adjust"` - these are describing **importing** plan rather than the imported one, as it's the importing plan that's examined and skipped when disabled. In that case there is no imported plan at all.

**Comment by pkhartsk** [comment]
My bad @happz , didn't realise the wording mattered.
>     * "Do not fetch disabled remote plans in tmt run" - actually, whether the remote plan is disabled or not is not relevant to your PR, as it skips import resolution if the **importing** (or "local") plan is disabled. The title should be something like "Do not resolve importing plan when it is disabled".

Will change.

>     * `/imported/disabled-by-adjust`, `summary: Imported plan should be disabled by default`,  `rlPhaseStartTest "Imported plan's import should not be resolved if disabled by adjust"` - these are describing **importing** plan rather than the imported one, as it's the importing plan that's examined and skipped when disabled. In that case there is no imported plan at all.

Would it be better to name it `/disabled-by-adjust`, "Local plan disabled by adjust should not import remote plan", and "Remote plan should not be fetched if disabled by adjust"?

**Comment by LecrisUT** [comment]
> Would it be better to name it /disabled-by-adjust, "Local plan disabled by adjust should not import remote plan", and "Remote plan should not be fetched if disabled by adjust"?

Oh indeed it seems identical up to the difference of having `adjust` considered or not. I would say it should be split into `/disabled/default` and `/disabled/by-adjust`.

But looking at the tests done for that one, it doesn't seem to do meaningful checks either. At the minimum I would expect it to check for the git cloning (there should be a specific place where the data is cloned to that can be used for the check). The complications is that we have multiple scenarios that we would need to confirm the git cloning is done or not:
- `tmt plans ls`
- `tmt plans ls` with `--shallow` or `--import-before-name-filter`
- `tmt plans show`
- `tmt run`

and how should the disablement of the parent affect these

File: tests/plan/import/basic.sh [hunk 1]
```diff
@@ -139,6 +139,11 @@ rlJournalStart
         rlRun -s "tmt -c how=full run -r --dry plan -n /plans/full/tmt" 0 "Run plan (dry mode)"
     rlPhaseEnd
 
+    rlPhaseStartTest "Remote plan should not be fetched if disabled by adjust"
+        rlRun -s "tmt -c distro=fedora-rawhide run --remove --dry plan --name /plans/disabled-by-adjust" 2 "Expect no plans to be found"
+        rlRun -s "tmt -c distro=fedora-rawhide -c how=full plan show /plans/disabled-by-adjust" 0 "Show plan correctly"
+    rlPhaseEnd
```
Comment (LecrisUT) [inline tests/plan/import/basic.sh:208]: You can run these with `-dd` and check `rlAssertNotGrep "Run command: git clone"` (we will improve it when switching to pytest). And also the debug message you just added.

Currently when no plans are enabled the output is `No plans found.` let's also check for that one.

File: tmt/base/core.py [hunk 2]
```diff
@@ -2626,6 +2626,13 @@ def plans(
             plans = []
             for plan in unresolved_plans:
                 try:
+                    # Do not resolve disabled plans during `tmt run`
+                    if run is not None and not plan.enabled:
+                        plan.debug(
+                            f"Plan {plan.name} is not enabled, skipping imports resolution",
+                            level=3,
+                        )
+                        continue
```
Comment (happz) [inline tmt/base/core.py]: This `if` block does not have to be under the `try/except` block.

File: tests/plan/import/data/plans.fmf [hunk 3]
```diff
@@ -62,6 +62,16 @@
             name: /plans/provision/connect
     enabled: true
 
+/disabled-by-adjust:
+    summary: Local plan disabled by adjust should not import remote plan
+    plan:
+        import:
+            url: https://github.com/teemtee/tmt
```
Comment (psss) [inline tests/plan/import/data/plans.fmf]: What about using here an inaccessible repository? For example:

```suggestion
            url: https://localhost/invalid
```

In this way we would clearly/simply verify that an unexpected `git clone` was not performed. And it would also reveal that the `tmt plan show` case is actually failing.

File: tmt/base/core.py [hunk 4]
```diff
@@ -2626,6 +2626,13 @@ def plans(
             plans = []
             for plan in unresolved_plans:
                 try:
+                    # Do not resolve disabled plans during `tmt run`
+                    if run is not None and not plan.enabled:
+                        plan.debug(
+                            f"Plan {plan.name} is not enabled, skipping imports resolution",
```
Comment (psss) [inline tmt/base/core.py]:
```suggestion
                            f"Plan '{plan.name}' is not enabled, skipping plan import during tmt run.",
```

File: tmt/base/core.py (hunk 2 above)
Comment (psss) [reply tmt/base/core.py]: Agreed.

**Review by psss — CHANGES_REQUESTED** [review]
Overall the approach [seems to be good](https://github.com/teemtee/tmt/issues/4757#issuecomment-4266254597). Added a couple suggestions. Do we want to cover the `tmt plan ls` and `tmt plan show` cases here as well? Or we keep the scope to `tmt run` only?

File: tmt/base/core.py [hunk 5]
```diff
@@ -2626,6 +2626,13 @@ def plans(
             plans = []
             for plan in unresolved_plans:
                 try:
+                    # Do not resolve disabled plans during `tmt run`
+                    if run is not None and not plan.enabled:
```
Comment (psss) [inline tmt/base/core.py]: Seems that in order to fix the `tmt plan ls --enabled` use case as well, the following would be sufficient?

```suggestion
                    if (run is not None or Plan._opt('enabled')) and not plan.enabled:
```

If the fix would be as simple as this (or similar complexity), I'd suggest to fix both use cases in this pull request.

File: tmt/base/core.py (hunk 4 above)
Comment (pkhartsk) [reply tmt/base/core.py]: This code now also runs during other commands then run, therefore "during tmt run" is no longer adequate.

File: tmt/base/core.py (hunk 5 above)
Comment (pkhartsk) [reply tmt/base/core.py]: Put something akin to this in the latest commit

File: tmt/base/core.py (hunk 2 above)
Comment (pkhartsk) [reply tmt/base/core.py]: Fixed

File: tests/plan/import/basic.sh (hunk 1 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh:208]: Fixed I hope

File: tests/plan/import/basic.sh [hunk 6]
```diff
@@ -9,134 +9,95 @@ rlJournalStart
...
-    rlPhaseEnd
-
-    rlPhaseStartTest "Imported plan's adjust should be respected"
-        rlRun -s "tmt run --remove --dry plan --name /plans/full/tmt" 2 "Expect error (dry mode)"
-        rlRun -s "tmt -c how=full run -r --dry plan -n /plans/full/tmt" 0 "Run plan (dry mode)"
+        rlAssertGrep "Found 11 plans" $rlRun_LOG
+    rlPhaseEnd
+
+
+    rlPhaseStartTest "Remote plan should not be fetched if disabled by adjust"
```
Comment (LecrisUT) [inline tests/plan/import/basic.sh:147]: Oh boy, what happened with all of the diff in this test?

Comment (pkhartsk) [reply tests/plan/import/basic.sh:147]: Right, removed everything and added mine, will bring them back

File: tests/plan/import/data/plans.fmf (hunk 3 above)
Comment (LecrisUT) [reply tests/plan/import/data/plans.fmf]: Still relevant. Can re-use the part in `/disabled-internal`. I don't remember the naming that we agreed on, but an organization like this could work
```yaml
/importing-disabled:
    plan:
        import:
            url: https://secret.internal
            name: /secret/internal/plan
    /default:
        enabled: false
    /by-adjust:
        enabled: true
        adjust:
            enabled: false
            when: some_context == disable
    /enabled-by-adjust:
        enabled: false
        adjust:
            enabled: false
            when: some_context == enable
```

File: tmt/base/core.py [hunk 7]
```diff
@@ -2624,10 +2622,20 @@ def plans(
...
+
         if not Plan._opt('shallow'):
             unresolved_plans = plans
             plans = []
             for plan in unresolved_plans:
+                # Do not resolve disabled plans unless forced to
+                if not resolve_disabled and not plan.enabled:
+                    plan.debug(
+                        f"Plan '{plan.name}' is not enabled, skipping imports resolution",
+                        level=3,
```
Comment (LecrisUT) [inline tmt/base/core.py]:
```suggestion
```
Let's make it more visible on the first debug level

File: tmt/base/core.py [hunk 8]
```diff
@@ -2548,6 +2545,7 @@ def plans(
         links: Optional[list['LinkNeedle']] = None,
         excludes: Optional[list[str]] = None,
         apply_command_line: bool = True,
+        resolve_disabled: bool = True,
```
Comment (LecrisUT) [inline tmt/base/core.py]: There's quite a bit of double-triple negation here? How about `enabled_only`?

File: tmt/cli/_root.py [hunk 9]
```diff
@@ -1101,7 +1101,7 @@ def plans_show(context: Context, /, **kwargs: Any) -> None:
 
     logger = context.obj.logger.clone().apply_verbosity_options(**kwargs)
 
-    for plan in context.obj.tree.plans(logger=logger):
+    for plan in context.obj.tree.plans(logger=logger, resolve_disabled=True):
```
Comment (LecrisUT) [inline tmt/cli/_root.py]: I think `plans_ls` would need a similar specification. Let's be more explicit for now to make sure we catch the correct behavior. Would be in favor of inverting the default since it is more conscious consideration how one would handle plans that are disabled.

**Review by LecrisUT — COMMENTED** [review]
Overall LGTM, just a style change, and the "what happened with the other tests"

File: tests/plan/import/data/plans.fmf (hunk 3 above)
Comment (pkhartsk) [reply tests/plan/import/data/plans.fmf]: Thing is that some tests I wrote rely on this one being importable, since I wanna test with the context being the desired value..

Comment (LecrisUT) [reply tests/plan/import/data/plans.fmf]: Couldn't catch the failure and make sure it fails in an expected way?

Comment (pkhartsk) [reply tests/plan/import/data/plans.fmf]: Just to reiterate, `plan show` should just say something like "couldn't fetch" but fail gracefully, right?

Comment (LecrisUT) [reply tests/plan/import/data/plans.fmf]: Maybe can do that in a different PR. I expect it to be quite tangential to everything else here, and would probably involve how we handle `--shallow` there as well. Handling `ls` could be either way, but would be important to be handled consistently to not disrupt testing-farm.

File: tests/plan/import/basic.sh [hunk 10]
```diff
@@ -9,134 +9,95 @@ rlJournalStart
...
+        rm -rf '~/.cache/fmf/https:__github.com_teemtee_tmt'
```
Comment (thrix) [inline tests/plan/import/basic.sh]: this will not expand correctly with the sundle quotes, will it?

File: tests/plan/import/data/plans.fmf (hunk 3 above)
Comment (psss) [reply tests/plan/import/data/plans.fmf]: Yeah, I'd say, let's keep the `tmt plan show` improvement for a separate pull request, there will be a bit more things to clarify for that part. Here I suggest to focus solely on:

* `tmt run`
* `tmt plan ls --enabled`

Comment (pkhartsk) [reply tests/plan/import/data/plans.fmf]: Ok, in that case I'll remove the `import_disabled` stuff and just keep that original change here.

Comment (psss) [reply tests/plan/import/data/plans.fmf]: I like the proposed plan structure, maybe with a couple adjustments:

```yaml
/inaccessible:
    plan:
        import:
            url: https://localhost/secret
            name: /secret/internal/plan
            
    /disabled:
        enabled: false
        
    /disabled-by-adjust:
        enabled: true
        adjust:
            enabled: false
            when: some_context == disable
            
    /enabled-by-adjust:
        enabled: false
        adjust:
            enabled: true
            when: some_context == enable
```

File: tests/plan/import/basic.sh (hunk 6 above)
Comment (psss) [reply tests/plan/import/basic.sh:147]: What about adding a new test script to cover these scenarios? They are not `basic` anymore... Perhaps `tests/plan/import/inaccessible.sh`?

File: tests/plan/import/basic.sh (hunk 10 above)
Comment (psss) [reply tests/plan/import/basic.sh]: Ack. If these are needed many times, let's define a short function for the cleanup? Another option could be `fmf clean` command (that would require `fmf` to be added to `require`).

File: tmt/base/core.py (hunk 8 above)
Comment (psss) [reply tmt/base/core.py]: The resolving is essential here I'd say, perhaps `resolve_enabled_only`?

File: tmt/base/core.py (hunk 4 above)
Comment (psss) [reply tmt/base/core.py]: Right.

File: tmt/base/core.py (hunk 5 above)
Comment (psss) [reply tmt/base/core.py]: Thanks!

File: tests/plan/import/basic.sh (hunk 10 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Fixed and separated into cleanup() function

File: tmt/base/core.py (hunk 8 above)
Comment (pkhartsk) [reply tmt/base/core.py]: Renamed

File: tmt/base/core.py (hunk 7 above)
Comment (pkhartsk) [reply tmt/base/core.py]: Fixed

File: tests/plan/import/basic.sh (hunk 6 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh:147]: Not sure separating one test case (with four sub-cases) makes much sense here. Maybe in the future when things like `plans show` get covered more correctly?

File: tests/plan/import/data/plans.fmf (hunk 3 above)
Comment (pkhartsk) [reply tests/plan/import/data/plans.fmf]: Added separate en/disabled-by-adjust for the importable and non-importable plan

File: tmt/base/core.py [hunk 11]
```diff
@@ -2624,10 +2622,19 @@ def plans(
...
+            resolve_enabled_only = True
+
         if not Plan._opt('shallow'):
             unresolved_plans = plans
             plans = []
             for plan in unresolved_plans:
+                # Do not resolve disabled plans unless forced to
+                if resolve_enabled_only and not plan.enabled:
+                    plan.debug(
+                        f"Plan '{plan.name}' is not enabled, skipping imports resolution",
```
Comment (psss) [inline tmt/base/core.py]:
```suggestion
                        f"Plan '{plan.name}' is not enabled, skipping imports resolution.",
```

A [consistency](https://tmt.readthedocs.io/en/stable/contribute.html#introduction) nitipick.

File: tmt/base/core.py
Comment (psss) [inline tmt/base/core.py]: Shouldn't we add `resolve_enabled_only=True` here as well? It will be auto-detected from the filters, but still, I'd say it would be good to make it explicit/clear that for `tmt run` we want this behaviour enabled.

File: tests/plan/import/basic.sh (hunk 6 above)
Comment (psss) [reply tests/plan/import/basic.sh:147]: It's quite a long one, so would still lean toward the separation, but not a blocker.

**Comment by psss** [comment]
@pkhartsk, could you please include a short release note? Thanks.

File: tests/plan/import/data/plans.fmf [hunk 12]
```diff
@@ -62,6 +62,47 @@
...
+        summary: Local plan enabled by adjust should import remote plan
+        adjust:
+            enabled: true
+            when: distro == fedora-rawhide
+        enabled: false
+
+/importing:
+    plan:
+        import:
+            url: https://github.com/teemtee/tmt
```
Comment (psss) [inline tests/plan/import/data/plans.fmf]:
```suggestion
            url: https://github.com/teemtee/tests
```

What about using the `tests` repo? It's smaller and thus faster.

**Comment by pkhartsk** [comment]
> @pkhartsk, could you please include a short release note? Thanks.

Where can I do that? I'm very much not orientated in this project :)

**Comment by LecrisUT** [comment]
> > @pkhartsk, could you please include a short release note? Thanks.
> 
> Where can I do that? I'm very much not orientated in this project :)

Yeah we should have clarified that :slightly_smiling_face:. See https://github.com/teemtee/tmt/blob/main/docs/releases/1.71.0/4661.fmf for example, but put it in `pending` folder, not the versioned one.

It is just a sphinx rst format with a fmf layer on top of it.

File: tests/plan/import/data/plans.fmf (hunk 12 above)
Comment (pkhartsk) [reply tests/plan/import/data/plans.fmf]: Fixed

File: tmt/base/core.py
Comment (pkhartsk) [reply tmt/base/core.py]: Done

File: tmt/base/core.py (hunk 11 above)
Comment (pkhartsk) [reply tmt/base/core.py]: Done.

File: tests/plan/import/basic.sh (hunk 6 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh:147]: Done

**Comment by pkhartsk** [comment]
Some of the tests in `basic.sh` don't pass cause show throws an error. Maybe for now it can be bypassed by filtering the `inaccessible` tests out?

**Comment by pkhartsk** [comment]
Also `run --dry` tests fail because of `The 'local' provision plugin requires '--feeling-safe' option.` No idea what that one is...

**Comment by LecrisUT** [comment]
> Some of the tests in `basic.sh` don't pass cause show throws an error. Maybe for now it can be bypassed by filtering the `inaccessible` tests out?

Or just filtering a specific subset. 2 options here:
- Make a new fmf root and similar to `data` for those
- Change the commands to only `tmt show` 1-2 plans

No preference either way from me.

> Also `run --dry` tests fail because of `The 'local' provision plugin requires '--feeling-safe' option.` No idea what that one is...

It is a can of worms :upside_down_face:, we lost track of that one as well. It has overlap with `--shallow`, but not sure how much more otherwise. I think the failure is more related to the plan in `teemtee/tests` that uses the `provision/local` rather than some container. Fine to add the `TMT_FEELING_SAFE=1` env var for that.

File: tests/plan/import/inaccessible.sh [hunk 13]
```diff
@@ -0,0 +1,30 @@
...
+
+rlJournalStart
+    rlPhaseStartSetup
+        rlRun "pushd data"
+    rlPhaseEnd
+
+    rlPhaseStartTest "Unimportable plan should not raise errors when disabled"
+        rlRun -s "tmt -ddd -c how=full plan ls /plans/inaccessible/disabled$" 2 "Error out when trying to import internal URL"
+        rlAssertGrep "Plan '/plans/inaccessible/disabled' importing" $rlRun_LOG
+        rlAssertGrep "Failed to import remote plan from '/plans/inaccessible/disabled'" $rlRun_LOG
```
Comment (LecrisUT) [inline tests/plan/import/inaccessible.sh:12]: - The `how=full` seems unnecessary here? Did you mean to set `distro` here? Fine to use whatever context variable though, and a custom one would help signal that it is not using the context that packit provides (and avoid confusion in code search)
- Can you split these 2 cases? The `rlPhaseStartTest` does not actually reflect that there are 2 cases in here.

File: tests/plan/import/basic.sh [hunk 14]
```diff
@@ -139,6 +143,75 @@ rlJournalStart
...
+        rlAssertGrep "Plan '/plans/importing/disabled-by-adjust' is not enabled, skipping imports resolution" $rlRun_LOG
+        rlAssertNotEquals "Verify last line is not the plan" "/plans/importing/disabled-by-adjust" $(tail -1 $rlRun_LOG)
+    rlPhaseEnd
+
+    rlPhaseStartTest "Disabled remote plan should be fetched if enabled by adjust"
+        cleanup
+        rlRun -s "tmt -ddd -c distro=fedora-rawhide -c how=full run --remove --dry plan --name /plans/importing/enabled-by-adjust" 0 "Run enabled plan"
+        rlAssertGrep "Plan '/plans/importing/enabled-by-adjust' importing" $rlRun_LOG
+        rlAssertNotGrep "Plan '/plans/importing/enabled-by-adjust' is not enabled, skipping imports resolution" $rlRun_LOG
+        rlAssertNotGrep "No plans found." $rlRun_LOG
```
Comment (LecrisUT) [inline tests/plan/import/basic.sh:181]: I think you can squeeze the `tmt run` case in the inacessible too right? Whether the plan is accessible or not, is not really relevant (other than the handling of the exit code) right? Is there something more specific that you want to catch with these?

At the very least these can be limited to just running `discover`

**Review by LecrisUT — COMMENTED** [review]
Implementation looks good, just figuring out how/what to test there.

File: tests/plan/import/inaccessible.sh (hunk 13 above)
Comment (pkhartsk) [reply tests/plan/import/inaccessible.sh:12]: `how=full` was there in all other `run`s so I just kept it there for consistency, can remove

Are these two cases? I'd call it one..

Comment (psss) [reply tests/plan/import/inaccessible.sh:12]: The `how=full` part is exercising/verifying that context `adjust` works for imported plans, in above tests is using the main `tmt` repo and `provision` plans which are enabled only under the `how=full` context.

File: tests/plan/import/basic.sh (hunk 14 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh:181]: Well this test already tests whether the adjust works, so I saw no point in writing the same thing with an inaccessible imported plan.

File: tests/plan/import/inaccessible.sh (hunk 13 above)
Comment (pkhartsk) [reply tests/plan/import/inaccessible.sh:12]: Ok, removed

File: docs/releases/pending/4749.fmf [hunk 15]
```diff
@@ -0,0 +1,4 @@
+description: |
+    Disabled remote plans in `run` and `plan ls --enabled`
```
Comment (psss) [inline docs/releases/pending/4749.fmf]:
```suggestion
    Disabled remote plans in ``tmt run`` and ``tmt plan ls --enabled``
```

File: tests/plan/import/inaccessible.sh [hunk 16]
```diff
@@ -0,0 +1,30 @@
+#!/bin/bash
```
Comment (psss) [inline tests/plan/import/inaccessible.sh:1]: In order to actually enable the test, please add test metadata similar to `basic.sh`:

https://github.com/teemtee/tmt/blob/c45b734376065966efe762cc8c173338e03a377c/tests/plan/import/main.fmf#L1-L3

File: tests/plan/import/inaccessible.sh (hunk 13 above)
Comment (LecrisUT) [reply tests/plan/import/inaccessible.sh:12]: > Are these two cases? I'd call it one..

Ah indeed so, I misread it. A comment of what is expected there or separating each command in its own phase would help. A `TODO` on the `tmt show` also since it's not a long-term expected behavior.

Can also remove the `-ddd` since it is not being used and parametrize the plan name? Mostly to help with the readability of what is relevant there

File: tests/plan/import/basic.sh [hunk 17]
```diff
@@ -1,19 +1,24 @@
...
     rlPhaseStartTest "Explore Plans"
         rlRun -s "tmt plan"
         rlAssertNotGrep "warn" $rlRun_LOG
-        rlAssertGrep "Found 9 plans" $rlRun_LOG
+        rlAssertGrep "Found 11 plans" $rlRun_LOG
     rlPhaseEnd
 
     rlPhaseStartTest "Show Plans (deep)"
-        rlRun -s "tmt plan show"
+        rlRun -s "tmt plan show '/plans/(?!inaccessible)'"
```
Comment (psss) [inline tests/plan/import/basic.sh]: Another option to avoid need for these negative patterns could be to move the inaccessible plans into a separate directory, use `pushd inaccessible` in `inaccessible.sh` and handle or related test cases which are using these plans there. Could be a bit more readable / maintainable? Just speaking aloud...

File: tests/plan/import/basic.sh (hunk 14 above)
Comment (LecrisUT) [reply tests/plan/import/basic.sh:181]: Well more like moving them since they primarily belong to the special case of "how do we handle disabled plans"

File: tests/plan/import/basic.sh [hunk 18]
```diff
@@ -139,7 +144,77 @@ rlJournalStart
         rlRun -s "tmt -c how=full run -r --dry plan -n /plans/full/tmt" 0 "Run plan (dry mode)"
     rlPhaseEnd
 
+    rlPhaseStartTest "Remote plan should not be fetched if disabled by adjust"
+        cleanup
+        rlRun -s "tmt -ddd -c distro=rhel-10 -c how=full run --remove --dry plan --name /plans/importing/disabled-by-adjust" 0 "Run enabled plan"
```
Comment (psss) [inline tests/plan/import/basic.sh]:
```suggestion
        rlRun -s "tmt -ddd -c distro=rhel-10 run --remove --dry plan --name /plans/importing/disabled-by-adjust" 0 "Run enabled plan"
```

Not need here and in test cases below as well.

File: tests/plan/import/basic.sh [hunk 19]
```diff
@@ -139,7 +144,77 @@ rlJournalStart
...
+
+        cleanup
+        rlRun -s "tmt -ddd -c distro=fedora-rawhide -c how=full run --remove --dry plan --name /plans/importing/disabled-by-adjust" 2 "Expect no plans to be found"
+        rlAssertNotGrep "Plan '/plans/importing/disabled-by-adjust' importing" $rlRun_LOG
+        rlAssertGrep "Plan '/plans/importing/disabled-by-adjust' is not enabled, skipping imports resolution" $rlRun_LOG
+        rlAssertGrep "No plans found." $rlRun_LOG
+
+        rlRun -s "tmt -ddd -c distro=fedora-rawhide -c how=full plan show /plans/importing/disabled-by-adjust --shallow" 0 "Show dummy plan"
+        rlAssertNotGrep "Plan '/plans/importing/disabled-by-adjust' importing" $rlRun_LOG
+
```
Comment (psss) [inline tests/plan/import/basic.sh]: Isn't the `--shallow` use case already covered by the `Show Plans (shallow)` phase above?

File: tests/plan/import/basic.sh [hunk 20]
```diff
@@ -139,7 +144,77 @@ rlJournalStart
...
+        rlAssertNotEquals "Verify last line is not the plan" "/plans/importing/enabled-by-adjust" $(tail -1 $rlRun_LOG)
+
+        rlRun -s "tmt -ddd -c distro=fedora-rawhide -c how=full plan ls /plans/importing/enabled-by-adjust --enabled" 0 "List enabled plans with correct environment"
+        rlAssertGrep "Plan '/plans/importing/enabled-by-adjust' importing" $rlRun_LOG
+        rlAssertNotGrep "Plan '/plans/importing/enabled-by-adjust' is not enabled, skipping imports resolution" $rlRun_LOG
+        rlAssertEquals "Verify last line is the plan" "/plans/importing/enabled-by-adjust" $(tail -1 $rlRun_LOG)
+    rlPhaseEnd
+
     rlPhaseStartCleanup
+        unset TMT_FEELING_SAFE
```
Comment (psss) [inline tests/plan/import/basic.sh]: No need to unset the variable, will be forgotten with the `shell` process end.

**Review by psss — CHANGES_REQUESTED** [review]
Thanks for the improvements! We're getting there! :) Added a couple more suggestions.

File: tests/plan/import/inaccessible.sh (hunk 13 above)
Comment (pkhartsk) [reply tests/plan/import/inaccessible.sh:12]: the -ddd is there for that `Plan '/plans/inaccessible/disabled' importing`

File: tests/plan/import/basic.sh (hunk 17 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Makes sense, would also make that `tmt plan` work in basic.sh

Comment (psss) [reply tests/plan/import/basic.sh]: Good, then let's take this approach :+1:

File: docs/releases/pending/4749.fmf (hunk 15 above)
Comment (pkhartsk) [reply docs/releases/pending/4749.fmf]: Fixed

File: tests/plan/import/inaccessible.sh (hunk 16 above)
Comment (pkhartsk) [reply tests/plan/import/inaccessible.sh:1]: Fixed

File: tests/plan/import/basic.sh (hunk 17 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Done

File: tests/plan/import/basic.sh (hunk 18 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Fixed

File: tests/plan/import/basic.sh (hunk 20 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Fixed

File: tests/plan/import/basic.sh (hunk 19 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Removed

**Comment by psss** [comment]
@pkhartsk, thanks for the improvements! Could you please rebase on the latest `main`? Thanks.

File: tests/plan/import/basic.sh [hunk 21]
```diff
@@ -33,7 +38,7 @@ rlJournalStart
     rlPhaseEnd
 
     rlPhaseStartTest "Show Plans (verbose, deep)"
-        rlRun -s "tmt plan show --verbose"
+        rlRun -s "tmt plan show  --verbose"
```
Comment (psss) [inline tests/plan/import/basic.sh]: Let's remove these no-op double spaces.

File: tests/plan/import/basic.sh (hunk 19 above)
Comment (psss) [reply tests/plan/import/basic.sh]: Test case seems to be still there.

File: tests/plan/import/basic.sh (hunk 21 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Done

File: tests/plan/import/basic.sh (hunk 19 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: My bad, should be done now

File: tmt/cli/_root.py (hunk 9 above)
Comment (LecrisUT) [reply tmt/cli/_root.py]: @pkhartsk can still add the explicit `kwarg` for `plans_ls` function also?

Comment (pkhartsk) [reply tmt/cli/_root.py]: Isn't it already tehre?

Comment (pkhartsk) [reply tmt/cli/_root.py]: Oh nvm, got it..

**Review by LecrisUT — APPROVED** [review]
LGTM, only non-blocking comment is about `/importing` tests if they should be moved together with `inaccessible.sh`. Would be fine either way since we can revisit it when we migrate the tests to `pytest`. Just comment on that thread if you plan to address it or not and I can resolve the thread for you (iirc external contributors cannot resolve threads on github)

File: tmt/cli/_root.py (hunk 9 above)
Comment (pkhartsk) [reply tmt/cli/_root.py]: Uhh, that broke things..
```
:: [ 17:50:00 ] :: [  BEGIN   ] :: List disabled plan :: actually running 'tmt -ddd -c distro=rhel-10 plan ls /plans/importing/enabled-by-adjust'
Plan '/plans/importing/enabled-by-adjust' is not enabled, skipping imports resolution.
:: [ 17:50:01 ] :: [   PASS   ] :: List disabled plan (Expected 0, got 0)
:: [ 17:50:01 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.w4HLuHQ5' should contain 'Plan '/plans/importing/enabled-by-adjust' importing' 
:: [ 17:50:01 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.w4HLuHQ5' should not contain 'Plan '/plans/importing/enabled-by-adjust' is not enabled, skipping imports resolution' 
:: [ 17:50:01 ] :: [   FAIL   ] :: Verify last line is the plan (Assert: '/plans/importing/enabled-by-adjust' should equal 'Plan')
```
Are we sure we want to only list enabled plans by defualt, what's the point of the `--enabled` flag then?

Comment (pkhartsk) [reply tmt/cli/_root.py]: Or you mean explicitly put `resolve_enabled_only=false`

Comment (pkhartsk) [reply tmt/cli/_root.py]: nevermind, im tired

File: tests/plan/import/basic.sh (hunk 14 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh:181]: > about `/importing` tests if they should be moved together with `inaccessible.sh`

Moving them makes no sense since we wanna test this in "accessible" scenarios, too.
Copying them is an option but I don't really see a point in doing so, it would just duplicate the tests..

Comment (LecrisUT) [reply tests/plan/import/basic.sh:181]: :+1: Sure. Main reason for the suggestion is that the `basic.sh` is very loaded at the moment, but this can be revisited when we migrate these anyway

File: tests/plan/import/basic.sh [hunk 22]
```diff
@@ -78,7 +83,7 @@ rlJournalStart
 
     rlPhaseStartTest "Discover Tests"
         # Exclude /plans/dynamic-ref as dynamic ref cannot be evaluated in dry mode
-        rlRun -s "tmt run --remove discover -v plan -n '/plans/(?!dynamic-ref)'"
+        rlRun -s "tmt run --remove discover -v plan -n '/plans/(?!(dynamic-ref))'"
```
Comment (psss) [inline tests/plan/import/basic.sh]:
```suggestion
        rlRun -s "tmt run --remove discover -v plan -n '/plans/(?!dynamic-ref)'"
```

Nitpick, unrelated change, not needed.

**Review by psss — APPROVED** [review]
Looks good! Thanks for fixing this. Just one nitpick.

**Comment by psss** [comment]
> LGTM, only non-blocking comment is about `/importing` tests if they should be moved together with `inaccessible.sh`.

They are not exactly exercising the inaccessible repositories scenario, so I'd say, they are just fine in `basic` as well.

File: tests/plan/import/basic.sh (hunk 22 above)
Comment (pkhartsk) [reply tests/plan/import/basic.sh]: Hopefully the last change I'll push to this branch :melting_face:
